name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
      - 'feature/*'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
      - 'feature/*'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        name: Checkout

      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 'v12.x'
          registry-url: 'https://registry.npmjs.org'
        name: Set up Node

      - name: Set package registry
        run: npm config set registry https://office.pkgs.visualstudio.com/_packaging/Office/npm/registry/

      - name: Office Feedback package registry authentication
        run: |
          npm set //office.pkgs.visualstudio.com/_packaging/Office/npm/registry/:username=office
          npm set //office.pkgs.visualstudio.com/_packaging/Office/npm/registry/:_password=NGh0NmRpY2M0N3B3N3dmM2hiM3plZXBveGRpcHNoeWEzejJjaGx1bGhtN2YyaWsyYnJ6YQ==
          npm set //office.pkgs.visualstudio.com/_packaging/Office/npm/registry/:email=japethobalak@gmail.com
          npm set //office.pkgs.visualstudio.com/_packaging/Office/npm/:username=office
          npm set //office.pkgs.visualstudio.com/_packaging/Office/npm/:_password=NGh0NmRpY2M0N3B3N3dmM2hiM3plZXBveGRpcHNoeWEzejJjaGx1bGhtN2YyaWsyYnJ6YQ==
          npm set //office.pkgs.visualstudio.com/_packaging/Office/npm/:email=japethobalak@gmail.com

      - name: Install Office Feedback package
        run: npm install -g @ms-ofb/officebrowserfeedbacknpm@1.6.4

      - name: Delete .npmrc file
        run: rm -i *.npmrc

      - name: Set package registry
        run: npm config set registry https://registry.npmjs.org

      - name: Config list
        run: npm config list

      - name: Build And Deploy
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0AC78C710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0AC78C710 }}
          action: "close"
